### ISSUE TITLE
TMDB TV Show Support

### ISSUE THREAD

**Issue by Fribb** [Fribb/anime-lists-generator#2]
based on: Fribb/anime-lists#18

TheMovieDB has supported TV Shows for a while now. The generator, however, specifically only does the lookup for IDs on TMDB when the type of the Anime-offline-Database JSON item is `MOVIE`.

Additional information for completion Sake:

anime-lists-reduced:
```
  {
    "thetvdb_id": 81830,
    "anidb_id": 5575
  },
```

anime-offline-database-reduced:

``` 
 {
    "livechart_id": 3687,
    "anime-planet_id": "kanokon",
    "anisearch_id": 4605,
    "anidb_id": 5575,
    "kitsu_id": 3056,
    "mal_id": 3503,
    "type": "TV",
    "notify.moe_id": "c59w5Fimg",
    "anilist_id": 3503
  },
```

Anime on TMDB: https://www.themoviedb.org/tv/46414-kanokon
External IDs for that Anime on TMDB: https://www.themoviedb.org/tv/46414-kanokon/edit?active_nav_item=external_ids

Both TVDB (81830) as well as IMDB (tt1216124) are listed there.

**Comment by kiam001** [comment]
Incidentally, the tmdb id is also linked on TVdb as Info 

https://www.thetvdb.com/series/81830/edit

**Comment by Fribb** [comment]
Good to hear, so far all requests and completing of the IDs were made with TheMovieDB since it provided a way to search for an external ID. And access to the API is free.

This looks to be available in the TVDB API now too through the [remoteid Endpoint](https://thetvdb.github.io/v4-api/#/Search/getSearchResultsByRemoteId) but I currently don't have an active API subscription to try that out and see if it really is what I think it is.

This would definitely make things easier because I could query both with an already existing ID and see what is coming back.

**Comment by Fribb** [comment]
This should now be addressed/fixed with commit 6c8f352

I will have to do some tests with my CI/CD that runs the generation automatically, if nothing is going seriously wrong there, the next automatic generation (next week) should see the changes.

**Comment by Azmarine13** [comment]
is there support for [SIMKL Anime](https://simkl.com/anime/) Id's ?
API: https://simkl.docs.apiary.io/#reference/anime

**Comment by Fribb** [comment]
No, no support for SIMKL as of right now.

But, this is the wrong place to talk about this since this issue is about TVDB ID lookup on TheMovieDB.

If you think this would be a good addition, please submit a new issue and then we can talk about this there.
